### ISSUE TITLE
Map drawing zeroes as line numbers

### ISSUE THREAD

**Issue by twolfson** [browniefed/pdxlivebus#3]
Hey there! I was trying to use out the website due to the snow making Google inaccurate with bus timings. Ironically, I'm guessing the app is having issues with the bus timings as well as it's showing 0's for some of the line numbers

![Screenshot of 0 line numbers](https://cloud.githubusercontent.com/assets/902488/21952905/c876e45a-d9dd-11e6-8f00-cf25bc9ec564.png)

I would love to dig deeper into this but I don't have enough time tonight =/

Also, it was hard to find this GitHub repo. I tried viewing the source and eventually went to a WHOIS lookup, then Google search for your name, and eventually found my way here. Maybe there should be a small "Support" or "GitHub" link in the footer like the leaflet text?

**Comment by browniefed** [comment]
Heh I'll be fixing up the app to be more useful shortly.
The app reports what Trimet sends me as the route number. So Trimet is literally sending me route 0 as the route number which is unfortunate
