### ISSUE TITLE
WebPack error when building `VehicleSocket.js`

### ISSUE THREAD

**Issue by ythecombinator** [browniefed/pdxlivebus#4]
> I wonder if maybe what I'm reporting here isn't a mistake of mine-then please point and I'll close the issue ASAP 😄 .

Hey, congrats for the project!

What happens is that every time I try to fire up the server(`npm run dev`) I get the following error:

```sh
ERROR in ./app/containers/VehicleSocket.js
Module not found: Error: Cannot resolve module 'socket.io-client/socket.io' in /Users/mabrasil/Documents/<...>/pdxlivebus/app/containers
 @ ./app/containers/VehicleSocket.js 80:9-46
```

The first thing I checked was if `socket.io-client` was listed in your `package.json`–and it was.

I have experimented adding the `noParse`, and `externals` as described in the following [thread](https://github.com/socketio/socket.io-client/issues/933). Also went on through [these](https://github.com/infinitered/reactotron/issues/48) [ones](https://github.com/socketio/socket.io/issues/2109)–and nothing works for me 😢 

> Here's my setup:
> 
> Node.js `v6.9.1`
> macOS Sierra `10.12.2`

Any thoughts?

**Comment by browniefed** [comment]
I assume you ran `npm install ` ?

**Comment by browniefed** [comment]
This will get a major update soon and also bring the server into the same repo as well.

**Comment by ythecombinator** [comment]
Sorry for the delay @browniefed 

Yes, I'd ran `npm install`.

**Comment by cathyleeu** [comment]
Hi! @ythecombinator 
i got a same issue with u so I tried to install 'socket.io-client' again.

and changed VehicleSocket.js 
`var io = require("socket.io-client/socket.io");`
to
`var io = require("socket.io-client");`

i think its work for you~
